### ISSUE TITLE
def initialize ＠a, ＠b; end

### ISSUE THREAD

**Issue by ne-sachirou** [ne-sachirou/AutoAttrInit.rb#3]
_cf._ RubyistたちのDRY症候群との戦い http://melborne.github.io/2013/09/27/auto-attr-set-in-ruby/

Now.

``` ruby
class Sample
  def initialize a, b; end
  auto_attr_set :a, :b
end
```

Proposal.

``` ruby
class Sample
  def initialize ＠a, ＠b; end
end
```

<code>＠a</code> is not <code>@a</code>. It's code point is different.

**Comment by ne-sachirou** [comment]
Problems.
1. ＠ (65312) is difficult to input by ASCII users. -> Can use at_ or this_ or self_ instead.
2. cannot omit anything. auto_attr_set with no params automaticaly set **all** params.

**Comment by melborne** [comment]
+1

**Comment by ne-sachirou** [comment]
他にも問題が有りますね。

全角＠を採用した場合、影響範囲は小さいでしょうが、at_だと影響が大き過ぎますし、self_やthis_も其れなりに影響が有りそうですから、影響範囲を狭める様にしなければなりません。然ふすると、refinmentsにするかincludeさせるかでせう。多分includeさせる事に成ります。だったらauto_attr_setを書かせる現在と、記述量は変わらない訳です。

``` ruby
require 'auto_attr_set'
class Sample
  def initialize a, b; end
  auto_attr_set
end
```

v.s.

``` ruby
require 'auto_attr_Set'
class Sample
  prepend AutoAttrSet::AutoAI
  def initialize ＠a, self_b; end
end
```

或いは、全角＠はdefaultで有効にして、includeすればself_も有効にする、等でせうか。

但し利点が有ります。

明示的に＠を書かなければならない、と云ふ点。自分が何をしてゐるか、失念する事は無い訳です。＠を省略出来ない、と云ふのは **利点** と考へた方が好い気がします。

**Comment by ne-sachirou** [comment]
方針を決めました。現状の auto_attr_set はそのまま残し、全角＠サポートを追加します。initializeの引数に全角＠付きの名前をしようすると、AFIと見做されます。此の場合、 auto_attr_set は不要です。includeも不要です。

後、此れ実装したらrubygems.orgに登録しますね。

**Comment by melborne** [comment]
良いように思います。auto_attr_initを挿す時点で'auto'に偽りありの感もあると言えばあるので。でもまさか、全角＠が日の目を見るとは! 全角文字APIはgem史上初？

**Comment by ne-sachirou** [comment]
此んな所ですかね。
https://github.com/ne-sachirou/AutoAttrInit.rb/compare/master...auto_attr_init_by_atmark_prefix

**Comment by ne-sachirou** [comment]
ところでBundlerでgemを組み立てやうとしてゐるのですが、rake buildに失敗しますね……(〃l _ l)

```
C:\Users\ne_Sachirou\BTSync\auto_attr_init.rb>bundle exec rake build --trace
現在のコード ページ: 932
Nothing matches:
** Invoke build (first_time)
** Execute build
Nothing matches:
rake aborted!
現在のコード ページ: 932
  Successfully built RubyGem
  Name: auto_attr_init
  Version: 0.0.1
  File: auto_attr_init-0.0.1.gem
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:150:in `sh'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:58:in `build_gem'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:40:in `block in install'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:228:in `call'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:228:in `block in execute'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:223:in `each'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:223:in `execute'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:166:in `block in invoke_with_call_chain'
C:/Ruby200-x64/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:159:in `invoke_with_call_chain'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:152:in `invoke'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:143:in `invoke_task'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:101:in `each'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
C:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:70:in `run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-0.9.6/bin/rake:37:in `<top (required)>'
C:/Ruby200-x64/bin/rake:23:in `load'
C:/Ruby200-x64/bin/rake:23:in `<main>'
Tasks: TOP => build
```

**Comment by ne-sachirou** [comment]
あいよ(〃l _ l)っ https://rubygems.org/gems/auto_attr_init
